language: c
env:
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.04.1
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.0
  - OCAML_VERSION=4.07.0+trunk
addons:
  apt:
    sources:
      - avsm
    packages:
      - opam
      - time
cache:
  directories:
    - $HOME/.opam
before_install:
  - export OPAMYES=1
  - export OPAMVERBOSE=1
  - opam init
  - opam switch ${OCAML_VERSION}
  - eval `opam config env`
  - opam install ocamlbuild ocamlfind
  - wget https://github.com/rlepigre/ocaml-earley/archive/master.zip
  - unzip master.zip
  - cd ocaml-earley-master
  - make && make install
  - cd ..
  - rm -r ocaml-earley-master master.zip
  - make
  - make
install:
  - make install
script:
  - echo "TESTS DISABLED FOR NOW..."
os:
  - linux
notifications:
  email:
    - christophe@raffalli.eu
    - rodolphe.lepigre@inria.fr
